import { useState, useEffect } from "react";

// material-ui
import { useTheme } from "@mui/material/styles";
// import { AllTransactions } from "store/action/index";

// third-party
import ReactApexChart from "react-apexcharts";
import { connect } from "react-redux";
// import { dispatch } from "store/index";
import { Spin } from "antd";
import ProgressBar from "react-bootstrap/ProgressBar";

// chart options

// ==============================|| CHART - REPEAT CUSTOMER CHART ||============================== //

const RepeatCustomerChart = ({ allcount }) => {
  const theme = useTheme();

  const { primary, secondary } = theme.palette.text;
  const line = theme.palette.divider;
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    // console.log("dhdhdh", allcount);
  }, [allcount]);
  return (
    <div className="container-fluid">
      <div className="row">
        <div
          className="col-md-5"
          style={{ marginTop: "40px", marginBottom: "40px" }}
        >
          <h4 style={{}}>Details Reports</h4>
          <span
            className="popins"
            style={{
              fontWeight: 900,
              fontSize: "28px",
              textTransform: "uppercase",
              letterSpacing: "2px",
            }}
          >
            ${allcount?.total_due_payment1}
          </span>

          <h5 style={{}}>E-Paisa Changer Company</h5>
          <h6
            style={{ color: "#FF264C", marginTop: "7px", lineHeight: "26px" }}
          >
            The Total Number of Revenue Generated By <br /> Your Properties
          </h6>
        </div>
        <div className="col-md-7" style={{ marginTop: "56px" }}>
          {/* <div style={{display:"flex",justifyContent:"space-evenly"}}>
        <p>Harmony Haven Residences </p>
        <ProgressBar style={{padding:"0px",width:"290px",marginTop:"4px",height:"14px"}}  variant="info"  label={90}   now={90} />


      </div> */}
          <div style={{ display: "flex", justifyContent: "space-evenly" }}>
            <p>Tenant Assign Property </p>
            <ProgressBar
              style={{
                padding: "0px",
                width: "290px",
                marginTop: "4px",
                marginLeft: "41px",
                height: "14px",
              }}
              variant="warning"
              label={
                allcount?.current_assigned_client !== undefined
                  ? `${allcount.current_assigned_client}%`
                  : "0%"
              }
              now={allcount?.current_assigned_client}
            />
          </div>
          <div style={{ display: "flex", justifyContent: "space-evenly" }}>
            <p>Balance Amount </p>
            <ProgressBar
              style={{
                padding: "0px",
                width: "290px",
                marginTop: "4px",
                marginLeft: "70px",
                height: "14px",
              }}
              variant="danger"
              label={
                allcount?.balance_amount !== undefined
                  ? `${allcount.balance_amount}%`
                  : "0%"
              }
              now={allcount?.balance_amount}
            />
          </div>
          <div style={{ display: "flex", justifyContent: "space-evenly" }}>
            <p>Un-Rented Property</p>
            <ProgressBar
              style={{
                padding: "0px",
                width: "290px",
                marginTop: "4px",
                marginLeft: "50px",
                height: "14px",
              }}
              variant="success"
              label={
                allcount?.available_property !== undefined
                  ? `${allcount.available_property}%`
                  : "0%"
              }
              now={allcount?.available_property}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

const mapStateToProps = (state) => {
  return {
    allcount: state?.AllCountReducers?.allcount,
  };
};

export default connect(mapStateToProps)(RepeatCustomerChart);
